[build-system]
requires = [
    "setuptools>=60",
    "setuptools-scm>=8.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tdac-seq"
dynamic = ["version"]
dependencies = []

[tool.setuptools]
packages = ["tdac_seq"]

[tool.setuptools_scm]
